# Generated by Django 5.0.4 on 2024-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='01833351531', max_length=11),
            preserve_default=False,
        ),
    ]
