# Generated by Django 5.0.4 on 2024-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=64)),
                ('object_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('object_piccture', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
