# Generated by Django 5.0.4 on 2024-04-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='object_piccture',
            new_name='object_picture',
        ),
    ]
