# Generated by Django 5.0.4 on 2024-04-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_id_listings_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='object_picture',
        ),
    ]
