# Generated by Django 5.0.4 on 2024-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listings_object_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='object_description',
            field=models.TextField(blank=True),
        ),
    ]
