# Generated by Django 5.0.4 on 2024-04-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='picture_URL',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
