# Generated by Django 5.0.4 on 2024-05-01 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_picture_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bid_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bidder_name', models.CharField(max_length=64)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listings')),
            ],
        ),
    ]
