# Generated by Django 5.0.4 on 2024-05-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlisted',
            field=models.ManyToManyField(to='auctions.listings'),
        ),
    ]
