# Generated by Django 5.0.4 on 2024-05-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_user_watchlisted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='bidder_name',
        ),
        migrations.AddField(
            model_name='bids',
            name='bidder_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
