# Generated by Django 5.0.4 on 2024-05-01 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_bids_bidder_name_bids_bidder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='current_bid',
            new_name='bid_amount',
        ),
    ]
