# Generated by Django 5.0.4 on 2024-05-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listings_object_lister'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='listing_open',
            field=models.BooleanField(default=True),
        ),
    ]
