# Generated by Django 5.0.4 on 2024-05-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_rename_object_lister_listings_object_lister_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='object_lister_id',
            new_name='object_lister',
        ),
    ]
