# Generated by Django 5.0.4 on 2024-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_categories_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_text',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
